apiVersion: v1
kind: Secret
metadata:
  name: assessify-secrets
  namespace: assessify
type: Opaque
stringData:
  DATABASE_URL: "postgresql://assessify:CHANGE_ME@postgres-service:5432/assessify?schema=public"
  JWT_ACCESS_SECRET: "CHANGE_THIS_ACCESS_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_THIS_REFRESH_SECRET"
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"
  S3_ENDPOINT: "https://s3.amazonaws.com"
  REDIS_PASSWORD: ""
